model_family: opt-1.3b

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU/full.json
split: full
batch_size: 1
gradient_accumulation_steps: 1
num_epochs: 5
lr: 1e-5
save_dir: models/finetune_opt1.3b_tofu
weight_decay: 0.01
